-- Each rerun replaces only this lab's schema.
DROP SCHEMA IF EXISTS lab07 CASCADE;
CREATE SCHEMA lab07;

-- Three ways to declare a single-column primary key.
CREATE TABLE lab07.inline_key (
    student_id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);
CREATE TABLE lab07.table_key (
    student_id INTEGER,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (student_id)
);
CREATE TABLE lab07.named_key (
    student_id INTEGER,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_named_student PRIMARY KEY (student_id)
);
CREATE TABLE lab07.added_key (
    student_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL
);
ALTER TABLE lab07.added_key ADD CONSTRAINT pk_added_student PRIMARY KEY (student_id);

INSERT INTO lab07.inline_key VALUES (1, 'Nurai');
INSERT INTO lab07.table_key VALUES (2, 'Alikhan');
INSERT INTO lab07.named_key VALUES (3, 'Aelita');
INSERT INTO lab07.added_key VALUES (4, 'Bekzat');

-- The same student can take the same course in another semester.
CREATE TABLE lab07.course_enrollments (
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    semester VARCHAR(20) NOT NULL,
    grade VARCHAR(2),
    PRIMARY KEY (student_id, course_id, semester)
);
INSERT INTO lab07.course_enrollments VALUES
    (1, 101, '2026-Spring', 'A'),
    (1, 102, '2026-Spring', 'B+'),
    (2, 101, '2026-Spring', 'A-'),
    (1, 101, '2026-Fall', 'A+');

-- PostgreSQL's automatic-number options.
CREATE TABLE lab07.products (
    product_id SERIAL PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL
);
CREATE TABLE lab07.transactions (
    transaction_id BIGSERIAL PRIMARY KEY,
    amount NUMERIC(15, 2) NOT NULL
);
CREATE TABLE lab07.orders (
    order_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL
);
CREATE TABLE lab07.customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL
);
INSERT INTO lab07.products (product_name) VALUES ('Notebook');
INSERT INTO lab07.transactions (amount) VALUES (250.00);
INSERT INTO lab07.orders (customer_name) VALUES ('Nurai');
INSERT INTO lab07.customers (customer_id, customer_name) VALUES (1000, 'VIP Customer');
INSERT INTO lab07.customers (customer_name) VALUES ('Regular Customer');

DO $$
BEGIN
    BEGIN
        INSERT INTO lab07.inline_key VALUES (1, 'Duplicate');
        RAISE EXCEPTION 'Duplicate primary key was accepted';
    EXCEPTION WHEN unique_violation THEN
        RAISE NOTICE 'PRIMARY KEY rejected a duplicate value';
    END;
    BEGIN
        INSERT INTO lab07.inline_key VALUES (NULL, 'Missing ID');
        RAISE EXCEPTION 'NULL primary key was accepted';
    EXCEPTION WHEN not_null_violation THEN
        RAISE NOTICE 'PRIMARY KEY rejected NULL';
    END;
    BEGIN
        INSERT INTO lab07.course_enrollments VALUES (1, 101, '2026-Spring', 'B');
        RAISE EXCEPTION 'Duplicate enrollment was accepted';
    EXCEPTION WHEN unique_violation THEN
        RAISE NOTICE 'Composite key rejected a duplicate enrollment';
    END;
    BEGIN
        INSERT INTO lab07.orders (order_id, customer_name) VALUES (1000, 'Explicit ID');
        RAISE EXCEPTION 'GENERATED ALWAYS accepted an explicit ID';
    EXCEPTION WHEN generated_always THEN
        RAISE NOTICE 'GENERATED ALWAYS rejected an explicit ID';
    END;
END $$;

SELECT * FROM lab07.course_enrollments ORDER BY student_id, course_id, semester;
SELECT product_id, product_name FROM lab07.products;
SELECT transaction_id, amount FROM lab07.transactions;
SELECT order_id, customer_name FROM lab07.orders;
SELECT customer_id, customer_name FROM lab07.customers ORDER BY customer_id;
SELECT tablename, indexname, indexdef
FROM pg_indexes WHERE schemaname = 'lab07' AND tablename IN ('inline_key', 'course_enrollments')
ORDER BY tablename, indexname;
